const FETCH_NAME_INFO: 'FETCH_NAME_INFO' = 'FETCH_NAME_INFO'
const FETCH_NODE_DATA: 'FETCH_NODE_DATA' = 'FETCH_NODE_DATA'
const FETCH_WALLET_INFO: 'FETCH_WALLET_INFO' = 'FETCH_WALLET_INFO'
const FETCH_SAVED_NAMES: 'FETCH_SAVED_NAMES' = 'FETCH_SAVED_NAMES'
const FETCH_SET_SAVED_NAME: 'FETCH_SET_SAVED_NAME' = 'FETCH_SET_SAVED_NAME'
const SET_HS_NODE: 'SET_HS_NODE' = 'SET_HS_NODE'
const SET_NODE_DATA: 'SET_NODE_DATA' = 'SET_NODE_DATA'
const SET_WALLET_INFO: 'SET_WALLET_INFO' = 'SET_WALLET_INFO'
const SET_WALLET_TX_HISTORY: 'SET_WALLET_TX_HISTORY' = 'SET_WALLET_TX_HISTORY'
const SET_NAME_INFO: 'SET_NAME_INFO' = 'SET_NAME_INFO'
const SET_SAVED_NAMES: 'SET_SAVED_NAMES' = 'SET_SAVED_NAMES'
const SELECT_NODE_DATA: 'SELECT_NODE_DATA' = 'SELECT_NODE_DATA'
const REMOVE_HS_NODE: 'REMOVE_HS_NODE' = 'REMOVE_HS_NODE'
const LOGOUT: 'LOGOUT' = 'LOGOUT'

export default {
  FETCH_NAME_INFO,
  FETCH_NODE_DATA,
  FETCH_WALLET_INFO,
  FETCH_SAVED_NAMES,
  FETCH_SET_SAVED_NAME,
  SET_HS_NODE,
  SET_NODE_DATA,
  SET_WALLET_INFO,
  SET_WALLET_TX_HISTORY,
  SET_NAME_INFO,
  SET_SAVED_NAMES,
  SELECT_NODE_DATA,
  REMOVE_HS_NODE,
  LOGOUT,
}
